// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@println.kr"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/certificates": {
            "get": {
                "description": "Get a list of all Certificate resources across all namespaces",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "certificates"
                ],
                "summary": "List all Certificates",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handler.CertificateResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new Certificate resource in the specified namespace",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "certificates"
                ],
                "summary": "Create a new Certificate",
                "parameters": [
                    {
                        "description": "Certificate to create",
                        "name": "certificate",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.CreateCertificateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handler.CertificateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/namespaces/{namespace}/certificates": {
            "get": {
                "description": "Get a list of Certificate resources in a specific namespace",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "certificates"
                ],
                "summary": "List Certificates in a namespace",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Namespace",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handler.CertificateResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/namespaces/{namespace}/certificates/{name}": {
            "get": {
                "description": "Get a specific Certificate resource by name and namespace",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "certificates"
                ],
                "summary": "Get a Certificate",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Namespace",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Certificate name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.CertificateResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update an existing Certificate resource",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "certificates"
                ],
                "summary": "Update a Certificate",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Namespace",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Certificate name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Certificate updates",
                        "name": "certificate",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.UpdateCertificateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.CertificateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a Certificate resource",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "certificates"
                ],
                "summary": "Delete a Certificate",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Namespace",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Certificate name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.CertificateResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "example-cert"
                },
                "namespace": {
                    "type": "string",
                    "example": "default"
                },
                "spec": {
                    "$ref": "#/definitions/handler.CertificateSpecResponse"
                },
                "status": {
                    "$ref": "#/definitions/handler.CertificateStatusResponse"
                }
            }
        },
        "handler.CertificateSpecResponse": {
            "type": "object",
            "properties": {
                "awsEnabled": {
                    "type": "boolean"
                },
                "awsSecretRef": {
                    "type": "string",
                    "example": "aws-credentials"
                },
                "cloudflareEnabled": {
                    "type": "boolean"
                },
                "cloudflareSecretRef": {
                    "type": "string",
                    "example": "cloudflare-credentials"
                },
                "cloudflareZoneID": {
                    "type": "string",
                    "example": "zone-id-123"
                },
                "clusterIssuerName": {
                    "type": "string",
                    "example": "letsencrypt-prod"
                },
                "domain": {
                    "type": "string",
                    "example": "example.com"
                }
            }
        },
        "handler.CertificateStatusResponse": {
            "type": "object",
            "properties": {
                "awsCertificateARN": {
                    "type": "string"
                },
                "awsUploaded": {
                    "type": "boolean"
                },
                "certificateRef": {
                    "type": "string"
                },
                "cloudflareCertificateID": {
                    "type": "string"
                },
                "cloudflareUploaded": {
                    "type": "boolean"
                },
                "lastUploadedCertHash": {
                    "type": "string"
                },
                "lastUploadedTime": {
                    "type": "string"
                }
            }
        },
        "handler.CreateCertificateRequest": {
            "type": "object",
            "required": [
                "domain",
                "name",
                "namespace"
            ],
            "properties": {
                "awsEnabled": {
                    "type": "boolean"
                },
                "awsSecretRef": {
                    "type": "string",
                    "example": "aws-credentials"
                },
                "cloudflareEnabled": {
                    "type": "boolean"
                },
                "cloudflareSecretRef": {
                    "type": "string",
                    "example": "cloudflare-credentials"
                },
                "cloudflareZoneID": {
                    "type": "string",
                    "example": "zone-id-123"
                },
                "clusterIssuerName": {
                    "type": "string",
                    "example": "letsencrypt-prod"
                },
                "domain": {
                    "type": "string",
                    "example": "example.com"
                },
                "name": {
                    "type": "string",
                    "example": "example-cert"
                },
                "namespace": {
                    "type": "string",
                    "example": "default"
                }
            }
        },
        "handler.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "resource not found"
                }
            }
        },
        "handler.UpdateCertificateRequest": {
            "type": "object",
            "properties": {
                "awsEnabled": {
                    "type": "boolean"
                },
                "awsSecretRef": {
                    "type": "string",
                    "example": "aws-credentials"
                },
                "cloudflareEnabled": {
                    "type": "boolean"
                },
                "cloudflareSecretRef": {
                    "type": "string",
                    "example": "cloudflare-credentials"
                },
                "cloudflareZoneID": {
                    "type": "string",
                    "example": "zone-id-123"
                },
                "clusterIssuerName": {
                    "type": "string",
                    "example": "letsencrypt-prod"
                },
                "domain": {
                    "type": "string",
                    "example": "example.com"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:8080",
	BasePath:    "/",
	Schemes:     []string{"http", "https"},
	Title:       "Certificate Operator API",
	Description: "REST API for managing Certificate custom resources in Kubernetes",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
